# Generated by Django 4.2.1 on 2025-04-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_game_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
