# Generated by Django 4.2.1 on 2025-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_instockmodel_game_in_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InStockModel',
        ),
        migrations.AlterField(
            model_name='game',
            name='in_stock',
            field=models.BooleanField(choices=[(1, 'В наличии'), (0, 'Нет в наличии')], default=1),
        ),
    ]
