# Generated by Django 4.2.1 on 2025-04-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category'),
        ),
    ]
