# Generated by Django 4.2.1 on 2025-04-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_taggame_game_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=255)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='catalog.game')),
            ],
        ),
    ]
